# Generated by Django 3.0.3 on 2020-09-20 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_upload_app', '0002_auto_20200906_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFileEncoded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cols_encoded', models.CharField(blank=True, max_length=400)),
                ('encoded_file_location', models.FileField(upload_to='encoded_files')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_upload_app.UserFileInfo')),
            ],
        ),
    ]
