# Generated by Django 3.0.3 on 2020-10-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_preproc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfileencoded',
            name='x_testData',
            field=models.TextField(blank=True, null=True, verbose_name='Independant variables Test Data'),
        ),
        migrations.AddField(
            model_name='userfileencoded',
            name='x_trainData',
            field=models.TextField(blank=True, null=True, verbose_name='Independant variables Training Data'),
        ),
        migrations.AddField(
            model_name='userfileencoded',
            name='y_PredData',
            field=models.TextField(blank=True, null=True, verbose_name='Dependant variables Predicted Data'),
        ),
        migrations.AddField(
            model_name='userfileencoded',
            name='y_testData',
            field=models.TextField(blank=True, null=True, verbose_name='Dependant variables Test Data'),
        ),
        migrations.AddField(
            model_name='userfileencoded',
            name='y_trainData',
            field=models.TextField(blank=True, null=True, verbose_name='Dependant variables Training Data'),
        ),
    ]
