# Generated by Django 3.0.3 on 2020-10-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_preproc_app', '0002_auto_20201011_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfileencoded',
            old_name='x_testData',
            new_name='x_TestData',
        ),
        migrations.RenameField(
            model_name='userfileencoded',
            old_name='x_trainData',
            new_name='x_TrainData',
        ),
        migrations.RenameField(
            model_name='userfileencoded',
            old_name='y_testData',
            new_name='y_TestData',
        ),
        migrations.RemoveField(
            model_name='userfileencoded',
            name='y_trainData',
        ),
        migrations.AddField(
            model_name='userfileencoded',
            name='y_TrainData',
            field=models.TextField(blank=True, null=True, verbose_name='Dependant variables Training Data'),
        ),
    ]
