# Generated by Django 3.0.3 on 2020-10-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_preproc_app', '0005_auto_20201011_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfileencoded',
            name='model_file_location',
        ),
    ]
