# Generated by Django 3.0.3 on 2020-09-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFile',
            new_name='UserFileInfo',
        ),
    ]
