# Generated by Django 3.0.3 on 2020-10-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_app', '0002_auto_20200906_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfileinfo',
            old_name='file_columns_list',
            new_name='file_dependent_column_name',
        ),
        migrations.AddField(
            model_name='userfileinfo',
            name='file_independent_columns_list',
            field=models.CharField(blank=True, max_length=355),
        ),
    ]
