# Generated by Django 3.0.3 on 2020-10-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_app', '0004_userfileinfo_model_file_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfileinfo',
            name='model_file_location',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
