# Generated by Django 3.0.3 on 2020-10-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_app', '0005_auto_20201011_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfileinfo',
            name='model_file_location',
        ),
        migrations.AddField(
            model_name='userfileinfo',
            name='model_Name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
