# Generated by Django 3.0.3 on 2020-10-21 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_app', '0006_auto_20201011_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModelDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scatter_digImage', models.ImageField(upload_to='images')),
                ('user_File_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_upload_app.UserFileInfo')),
            ],
        ),
    ]
