# Generated by Django 3.0.3 on 2020-10-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_app', '0007_usermodeldetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodeldetails',
            name='user_File_id',
        ),
    ]
