# Generated by Django 3.0.3 on 2020-10-23 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_app', '0009_auto_20201022_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodeldetails',
            name='user_File_id',
            field=models.ForeignKey(default=210, on_delete=django.db.models.deletion.CASCADE, to='data_upload_app.UserFileInfo'),
            preserve_default=False,
        ),
    ]
