# Generated by Django 3.0.3 on 2020-10-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_app', '0010_usermodeldetails_user_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodeldetails',
            name='scatter_digImage',
            field=models.ImageField(upload_to='model_generated_app'),
        ),
    ]
