# Generated by Django 3.0.3 on 2020-11-07 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_app', '0012_auto_20201025_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfileinfo',
            name='file_uploaded_by_user',
            field=models.FileField(upload_to='userfiles', validators=[django.core.validators.FileExtensionValidator(['csv'])], verbose_name='Select file to analyze'),
        ),
    ]
