# Generated by Django 3.0.3 on 2020-11-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_upload_app', '0013_auto_20201107_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfileinfo',
            name='file_uploaded_by_user',
            field=models.FileField(upload_to='userfiles', verbose_name='Select file to analyze'),
        ),
    ]
